# Generated by Django 5.2.17 on 2026-09-23 00:18

import django.db.models.deletion
import tournaments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('format_kind', models.CharField(blank=True, choices=[('rr', 'Round robin'), ('se', 'Single elimination'), ('de', 'Double elimination'), ('swiss', 'Swiss ladder'), ('rr_playoff', 'Round robin → playoffs'), ('custom', 'Custom')], max_length=12)),
                ('format_params', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['venue__order', 'venue_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('rr', 'Round robin'), ('se', 'Single elimination'), ('de', 'Double elimination'), ('swiss', 'Swiss')], max_length=6)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tiebreakers', models.JSONField(blank=True, default=list)),
                ('game_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('advanced_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournaments.category')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournaments.stage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('source_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.pool')),
                ('source_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='tournaments.pool')),
                ('source_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='tournaments.stage')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('short_name', models.CharField(blank=True, max_length=12)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.category')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('bracket', models.CharField(blank=True, max_length=1)),
                ('round', models.PositiveIntegerField(default=1)),
                ('index', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('home_prev_outcome', models.CharField(blank=True, max_length=1)),
                ('away_prev_outcome', models.CharField(blank=True, max_length=1)),
                ('home_bye', models.BooleanField(default=False)),
                ('away_bye', models.BooleanField(default=False)),
                ('manual_teams', models.BooleanField(default=False)),
                ('place_winner', models.PositiveIntegerField(blank=True, null=True)),
                ('place_loser', models.PositiveIntegerField(blank=True, null=True)),
                ('if_necessary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('forfeit', 'Forfeit'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('winner_side', models.CharField(blank=True, max_length=1)),
                ('forfeit_side', models.CharField(blank=True, max_length=1)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=60)),
                ('queue_order', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('away_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.entry')),
                ('away_prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.game')),
                ('home_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.entry')),
                ('home_prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.game')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.pool')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='tournaments.space')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.stage')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.team')),
            ],
            options={
                'ordering': ['stage__order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='tournaments.team'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('sport', models.CharField(choices=[('volleyball', 'Volleyball'), ('beach_volleyball', 'Beach volleyball'), ('soccer', 'Soccer'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('squash', 'Squash'), ('tennis', 'Tennis'), ('pickleball', 'Pickleball'), ('hockey', 'Hockey'), ('baseball', 'Baseball'), ('softball', 'Softball'), ('ultimate', 'Ultimate'), ('other', 'Other')], default='volleyball', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('banner', models.FileField(blank=True, upload_to='banners/')),
                ('visibility', models.CharField(choices=[('public', 'Public (listed)'), ('unlisted', 'Unlisted (anyone with the link)'), ('private', 'Private (admins only)')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='draft', max_length=12)),
                ('schedule_mode', models.CharField(choices=[('timed', 'Assigned times and spaces'), ('queue', 'Next available space (queue)')], default='timed', max_length=10)),
                ('points_win', models.IntegerField(default=3)),
                ('points_draw', models.IntegerField(default=1)),
                ('points_loss', models.IntegerField(default=0)),
                ('allow_draws', models.BooleanField(default=False)),
                ('forfeit_win_score', models.PositiveIntegerField(default=1)),
                ('forfeit_loss_score', models.PositiveIntegerField(default=0)),
                ('default_game_minutes', models.PositiveIntegerField(default=60)),
                ('buffer_minutes', models.PositiveIntegerField(default=0)),
                ('min_rest_minutes', models.PositiveIntegerField(default=0)),
                ('slot_interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('scorekeeper', 'Scorekeeper')], default='admin', max_length=12)),
                ('token', models.CharField(default=tournaments.models._token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('info', 'Important information'), ('venues', 'Venues'), ('categories', 'Categories'), ('sponsors', 'Sponsors'), ('links', 'Links'), ('image', 'Image')], default='text', max_length=12)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=list)),
                ('image', models.FileField(blank=True, upload_to='blocks/')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tournaments.tournament')),
            ],
            options={
                'verbose_name_plural': 'activity',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='space',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='tournaments.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('pool', 'position')},
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('scorekeeper', 'Scorekeeper')], max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
